# Non - Textual Data PreProcessing

In [1]:

import pandas as pd

df = pd.read_csv("C:/MIMIC Structured dataset/mimic-iv-3.1/hosp/diagnoses_icd.csv")

# convert to string (IMPORTANT)
df['icd_code'] = df['icd_code'].astype(str)

# cardiac arrest codes
ca_codes = ['4275', 'I46', 'I462', 'I468', 'I469']

# filter
df_ca = df[df['icd_code'].str.startswith(tuple(ca_codes))]

df_ca.head()

       subject_id   hadm_id  seq_num icd_code  icd_version
933      10001884  26184834       10     I469           10
6654     10009823  22096005       13     I469           10
7124     10010471  29842315        3     I462           10
8929     10013569  27993048        2     4275            9
13850    10021454  29492087        1     I469           10

In [2]:
df_ca

         subject_id   hadm_id  seq_num icd_code  icd_version
933        10001884  26184834       10     I469           10
6654       10009823  22096005       13     I469           10
7124       10010471  29842315        3     I462           10
8929       10013569  27993048        2     4275            9
13850      10021454  29492087        1     I469           10
...             ...       ...      ...      ...          ...
6352563    19983257  21588174       14     4275            9
6352835    19984052  25784208        5     I469           10
6357795    19990427  29695607       21     I469           10
6359705    19993336  23077223        2     I468           10
6361566    19995832  27920456        2     I462           10

[2665 rows x 5 columns]

In [3]:
#Merging ICU stays

In [4]:
icu = pd.read_csv("C:/MIMIC Structured dataset/mimic-iv-3.1/icu/icustays.csv")

df_cohort = df_ca.merge(icu, on=['subject_id', 'hadm_id'])

In [5]:
#Add demographics

In [6]:
patients = pd.read_csv("C:/MIMIC Structured dataset/mimic-iv-3.1/hosp/patients.csv")

df_cohort = df_cohort.merge(patients, on='subject_id')

In [7]:
admissions = pd.read_csv("C:/MIMIC Structured dataset/mimic-iv-3.1/hosp/admissions.csv")

df_cohort = df_cohort.merge(admissions[['hadm_id','deathtime','dischtime']], on='hadm_id')

df_cohort['mortality'] = (df_cohort['deathtime'] <= df_cohort['dischtime']).astype(int)

In [8]:
df_cohort.shape

(2896, 19)

In [9]:
df_cohort.head()

,subject_id,hadm_id,seq_num,icd_code,icd_version,stay_id,first_careunit,last_careunit,intime,outtime,los,gender,anchor_age,anchor_year,anchor_year_group,dod,deathtime,dischtime,mortality
0,10001884,26184834,10,I469,10,37510196,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2131-01-11 04:20:05,2131-01-20 08:27:30,9.171817,F,68,2122,2008 - 2010,2131-01-20,2131-01-20 05:15:00,2131-01-20 05:15:00,1
1,10009823,22096005,13,I469,10,31805686,Neuro Surgical Intensive Care Unit (Neuro SICU),Neuro Surgical Intensive Care Unit (Neuro SICU),2150-12-06 06:46:10,2150-12-06 20:33:52,0.574792,F,45,2150,2020 - 2022,2150-12-06,2150-12-06 14:22:00,2150-12-06 14:22:00,1
2,10010471,29842315,3,I462,10,32119961,Coronary Care Unit (CCU),Coronary Care Unit (CCU),2155-12-02 20:33:00,2155-12-07 18:19:18,4.907153,F,89,2155,2014 - 2016,2155-12-07,2155-12-07 15:30:00,2155-12-07 15:30:00,1
3,10013569,27993048,2,4275,9,38857852,Coronary Care Unit (CCU),Coronary Care Unit (CCU),2167-11-26 16:26:07,2167-12-05 16:53:53,9.019282,F,54,2165,2008 - 2010,NaN,NaN,2167-12-25 14:53:00,0
4,10013569,27993048,2,4275,9,39673498,Coronary Care Unit (CCU),Coronary Care Unit (CCU),2167-12-10 18:23:25,2167-12-18 18:16:14,7.995012,F,54,2165,2008 - 2010,NaN,NaN,2167-12-25 14:53:00,0

In [10]:
#Removing the duplicate icu stays and keeping only first icu stays

In [11]:
df_cohort = df_cohort.sort_values(by=['subject_id','intime'])
df_cohort = df_cohort.groupby('subject_id').first().reset_index()

In [12]:
# loading the chartevents datasets (40gb wala)

In [13]:
import pandas as pd

stay_ids = set(df_cohort['stay_id'])

filtered_chunks = []

chunks = pd.read_csv(
    "C:/MIMIC Structured dataset/mimic-iv-3.1/icu/chartevents.csv",
    usecols=['stay_id','itemid','charttime','valuenum'],
    chunksize=100000
)

for i, chunk in enumerate(chunks):
    chunk = chunk[chunk['stay_id'].isin(stay_ids)]
    filtered_chunks.append(chunk)

    if i % 10 == 0:
        print(f"Processed {i} chunks")

df_chartevents = pd.concat(filtered_chunks, ignore_index=True)

df_chartevents.shape

Processed 0 chunks
Processed 10 chunks
Processed 20 chunks
Processed 30 chunks
Processed 40 chunks
Processed 50 chunks
Processed 60 chunks
Processed 70 chunks
Processed 80 chunks
Processed 90 chunks
Processed 100 chunks
Processed 110 chunks
Processed 120 chunks
Processed 130 chunks
Processed 140 chunks
Processed 150 chunks
Processed 160 chunks
Processed 170 chunks
Processed 180 chunks
Processed 190 chunks
Processed 200 chunks
Processed 210 chunks
Processed 220 chunks
Processed 230 chunks
Processed 240 chunks
Processed 250 chunks
Processed 260 chunks
Processed 270 chunks
Processed 280 chunks
Processed 290 chunks
Processed 300 chunks
Processed 310 chunks
Processed 320 chunks
Processed 330 chunks
Processed 340 chunks
Processed 350 chunks
Processed 360 chunks
Processed 370 chunks
Processed 380 chunks
Processed 390 chunks
Processed 400 chunks
Processed 410 chunks
Processed 420 chunks
Processed 430 chunks
Processed 440 chunks
Processed 450 chunks
Processed 460 chunks
Processed 470 chunks
Processed 480 chunks
Processed 490 chunks
Processed 500 chunks
Processed 510 chunks
Processed 520 chunks
Processed 530 chunks
Processed 540 chunks
Processed 550 chunks
Processed 560 chunks
Processed 570 chunks
Processed 580 chunks
Processed 590 chunks
Processed 600 chunks
Processed 610 chunks
Processed 620 chunks
Processed 630 chunks
Processed 640 chunks
Processed 650 chunks
Processed 660 chunks
Processed 670 chunks
Processed 680 chunks
Processed 690 chunks
Processed 700 chunks
Processed 710 chunks
Processed 720 chunks
Processed 730 chunks
Processed 740 chunks
Processed 750 chunks
Processed 760 chunks
Processed 770 chunks
Processed 780 chunks
Processed 790 chunks
Processed 800 chunks
Processed 810 chunks
Processed 820 chunks
Processed 830 chunks
Processed 840 chunks
Processed 850 chunks
Processed 860 chunks
Processed 870 chunks
Processed 880 chunks
Processed 890 chunks
Processed 900 chunks
Processed 910 chunks
Processed 920 chunks
Processed 930 chunks
Processed 940 chunks
Processed 950 chunks
Processed 960 chunks
Processed 970 chunks
Processed 980 chunks
Processed 990 chunks
Processed 1000 chunks
Processed 1010 chunks
Processed 1020 chunks
Processed 1030 chunks
Processed 1040 chunks
Processed 1050 chunks
Processed 1060 chunks
Processed 1070 chunks
Processed 1080 chunks
Processed 1090 chunks
Processed 1100 chunks
Processed 1110 chunks
Processed 1120 chunks
Processed 1130 chunks
Processed 1140 chunks
Processed 1150 chunks
Processed 1160 chunks
Processed 1170 chunks
Processed 1180 chunks
Processed 1190 chunks
Processed 1200 chunks
Processed 1210 chunks
Processed 1220 chunks
Processed 1230 chunks
Processed 1240 chunks
Processed 1250 chunks
Processed 1260 chunks
Processed 1270 chunks
Processed 1280 chunks
Processed 1290 chunks
Processed 1300 chunks
Processed 1310 chunks
Processed 1320 chunks
Processed 1330 chunks
Processed 1340 chunks
Processed 1350 chunks
Processed 1360 chunks
Processed 1370 chunks
Processed 1380 chunks
Processed 1390 chunks
Processed 1400 chunks
Processed 1410 chunks
Processed 1420 chunks
Processed 1430 chunks
Processed 1440 chunks
Processed 1450 chunks
Processed 1460 chunks
Processed 1470 chunks
Processed 1480 chunks
Processed 1490 chunks
Processed 1500 chunks
Processed 1510 chunks
Processed 1520 chunks
Processed 1530 chunks
Processed 1540 chunks
Processed 1550 chunks
Processed 1560 chunks
Processed 1570 chunks
Processed 1580 chunks
Processed 1590 chunks
Processed 1600 chunks
Processed 1610 chunks
Processed 1620 chunks
Processed 1630 chunks
Processed 1640 chunks
Processed 1650 chunks
Processed 1660 chunks
Processed 1670 chunks
Processed 1680 chunks
Processed 1690 chunks
Processed 1700 chunks
Processed 1710 chunks
Processed 1720 chunks
Processed 1730 chunks
Processed 1740 chunks
Processed 1750 chunks
Processed 1760 chunks
Processed 1770 chunks
Processed 1780 chunks
Processed 1790 chunks
Processed 1800 chunks
Processed 1810 chunks
Processed 1820 chunks
Processed 1830 chunks
Processed 1840 chunks
Processed 1850 chunks
Processed 1860 chunks
Processed 1870 chunks
Processed 1880 chunks
Processed 1890 chunks
Processed 1900 chunks
Processed 1910 chunks
Processed 1920 chunks
Processed 1930 chunks
Processed 1940 chunks
Processed 1950 chunks
Processed 1960 chunks
Processed 1970 chunks
Processed 1980 chunks
Processed 1990 chunks
Processed 2000 chunks
Processed 2010 chunks
Processed 2020 chunks
Processed 2030 chunks
Processed 2040 chunks
Processed 2050 chunks
Processed 2060 chunks
Processed 2070 chunks
Processed 2080 chunks
Processed 2090 chunks
Processed 2100 chunks
Processed 2110 chunks
Processed 2120 chunks
Processed 2130 chunks
Processed 2140 chunks
Processed 2150 chunks
Processed 2160 chunks
Processed 2170 chunks
Processed 2180 chunks
Processed 2190 chunks
Processed 2200 chunks
Processed 2210 chunks
Processed 2220 chunks
Processed 2230 chunks
Processed 2240 chunks
Processed 2250 chunks
Processed 2260 chunks
Processed 2270 chunks
Processed 2280 chunks
Processed 2290 chunks
Processed 2300 chunks
Processed 2310 chunks
Processed 2320 chunks
Processed 2330 chunks
Processed 2340 chunks
Processed 2350 chunks
Processed 2360 chunks
Processed 2370 chunks
Processed 2380 chunks
Processed 2390 chunks
Processed 2400 chunks
Processed 2410 chunks
Processed 2420 chunks
Processed 2430 chunks
Processed 2440 chunks
Processed 2450 chunks
Processed 2460 chunks
Processed 2470 chunks
Processed 2480 chunks
Processed 2490 chunks
Processed 2500 chunks
Processed 2510 chunks
Processed 2520 chunks
Processed 2530 chunks
Processed 2540 chunks
Processed 2550 chunks
Processed 2560 chunks
Processed 2570 chunks
Processed 2580 chunks
Processed 2590 chunks
Processed 2600 chunks
Processed 2610 chunks
Processed 2620 chunks
Processed 2630 chunks
Processed 2640 chunks
Processed 2650 chunks
Processed 2660 chunks
Processed 2670 chunks
Processed 2680 chunks
Processed 2690 chunks
Processed 2700 chunks
Processed 2710 chunks
Processed 2720 chunks
Processed 2730 chunks
Processed 2740 chunks
Processed 2750 chunks
Processed 2760 chunks
Processed 2770 chunks
Processed 2780 chunks
Processed 2790 chunks
Processed 2800 chunks
Processed 2810 chunks
Processed 2820 chunks
Processed 2830 chunks
Processed 2840 chunks
Processed 2850 chunks
Processed 2860 chunks
Processed 2870 chunks
Processed 2880 chunks
Processed 2890 chunks
Processed 2900 chunks
Processed 2910 chunks
Processed 2920 chunks
Processed 2930 chunks
Processed 2940 chunks
Processed 2950 chunks
Processed 2960 chunks
Processed 2970 chunks
Processed 2980 chunks
Processed 2990 chunks
Processed 3000 chunks
Processed 3010 chunks
Processed 3020 chunks
Processed 3030 chunks
Processed 3040 chunks
Processed 3050 chunks
Processed 3060 chunks
Processed 3070 chunks
Processed 3080 chunks
Processed 3090 chunks
Processed 3100 chunks
Processed 3110 chunks
Processed 3120 chunks
Processed 3130 chunks
Processed 3140 chunks
Processed 3150 chunks
Processed 3160 chunks
Processed 3170 chunks
Processed 3180 chunks
Processed 3190 chunks
Processed 3200 chunks
Processed 3210 chunks
Processed 3220 chunks
Processed 3230 chunks
Processed 3240 chunks
Processed 3250 chunks
Processed 3260 chunks
Processed 3270 chunks
Processed 3280 chunks
Processed 3290 chunks
Processed 3300 chunks
Processed 3310 chunks
Processed 3320 chunks
Processed 3330 chunks
Processed 3340 chunks
Processed 3350 chunks
Processed 3360 chunks
Processed 3370 chunks
Processed 3380 chunks
Processed 3390 chunks
Processed 3400 chunks
Processed 3410 chunks
Processed 3420 chunks
Processed 3430 chunks
Processed 3440 chunks
Processed 3450 chunks
Processed 3460 chunks
Processed 3470 chunks
Processed 3480 chunks
Processed 3490 chunks
Processed 3500 chunks
Processed 3510 chunks
Processed 3520 chunks
Processed 3530 chunks
Processed 3540 chunks
Processed 3550 chunks
Processed 3560 chunks
Processed 3570 chunks
Processed 3580 chunks
Processed 3590 chunks
Processed 3600 chunks
Processed 3610 chunks
Processed 3620 chunks
Processed 3630 chunks
Processed 3640 chunks
Processed 3650 chunks
Processed 3660 chunks
Processed 3670 chunks
Processed 3680 chunks
Processed 3690 chunks
Processed 3700 chunks
Processed 3710 chunks
Processed 3720 chunks
Processed 3730 chunks
Processed 3740 chunks
Processed 3750 chunks
Processed 3760 chunks
Processed 3770 chunks
Processed 3780 chunks
Processed 3790 chunks
Processed 3800 chunks
Processed 3810 chunks
Processed 3820 chunks
Processed 3830 chunks
Processed 3840 chunks
Processed 3850 chunks
Processed 3860 chunks
Processed 3870 chunks
Processed 3880 chunks
Processed 3890 chunks
Processed 3900 chunks
Processed 3910 chunks
Processed 3920 chunks
Processed 3930 chunks
Processed 3940 chunks
Processed 3950 chunks
Processed 3960 chunks
Processed 3970 chunks
Processed 3980 chunks
Processed 3990 chunks
Processed 4000 chunks
Processed 4010 chunks
Processed 4020 chunks
Processed 4030 chunks
Processed 4040 chunks
Processed 4050 chunks
Processed 4060 chunks
Processed 4070 chunks
Processed 4080 chunks
Processed 4090 chunks
Processed 4100 chunks
Processed 4110 chunks
Processed 4120 chunks
Processed 4130 chunks
Processed 4140 chunks
Processed 4150 chunks
Processed 4160 chunks
Processed 4170 chunks
Processed 4180 chunks
Processed 4190 chunks
Processed 4200 chunks
Processed 4210 chunks
Processed 4220 chunks
Processed 4230 chunks
Processed 4240 chunks
Processed 4250 chunks
Processed 4260 chunks
Processed 4270 chunks
Processed 4280 chunks
Processed 4290 chunks
Processed 4300 chunks
Processed 4310 chunks
Processed 4320 chunks

(18532890, 4)

In [14]:
df_chartevents.head()

    stay_id            charttime  itemid  valuenum
0  37510196  2131-01-18 04:19:00  227944       NaN
1  37510196  2131-01-18 04:19:00  227945       NaN
2  37510196  2131-01-18 04:19:00  227946       NaN
3  37510196  2131-01-18 04:19:00  227947       NaN
4  37510196  2131-01-18 04:19:00  227948       NaN

In [15]:
df_chartevents['itemid'].value_counts().head(20)

itemid
227969    428271
220045    351084
220210    346407
220277    338111
220048    316085
224650    271715
227958    210517
220181    171893
220179    171853
220180    171827
220052    166504
220050    165665
220051    165619
228928    161977
228905    149883
224080    131076
224082    129716
224093    124935
224086    122291
228924    111361
Name: count, dtype: int64

In [16]:
# from this chartevents file we will extract the vital sign like  heart rate (HR), systolic/diastolic/mean
#blood pressure (SBP, DBP, MBP), respiratory rate (RR), body temperature (BT), and
#oxygen saturation (SpO2)

In [17]:
#filtering important vitals

vital_itemids = [
    220045,  # Heart Rate
    220210,  # Respiratory Rate
    220277,  # SpO2
    220179,  # SBP
    220180,  # DBP
    220181   # MBP
]

df_vitals = df_chartevents[df_chartevents['itemid'].isin(vital_itemids)]

In [18]:
# Removing NaN wala rows (if the value is a string like text data then it will show NaN and if it is numeric value then it will show the respective numbeer

In [19]:
df_vitals = df_vitals.dropna(subset=['valuenum'])

In [20]:
df_vitals.head()

     stay_id            charttime  itemid  valuenum
34  37510196  2131-01-11 06:00:00  220045      72.0
36  37510196  2131-01-11 06:00:00  220210      20.0
37  37510196  2131-01-11 06:00:00  220277     100.0
38  37510196  2131-01-11 06:01:00  220179     102.0
39  37510196  2131-01-11 06:01:00  220180      63.0

In [21]:
# here we are using vital signs for only 24 hours

In [22]:
# converting to datetime
df_vitals['charttime'] = pd.to_datetime(df_vitals['charttime'])
df_cohort['intime'] = pd.to_datetime(df_cohort['intime'])

# merging intime
df_vitals = df_vitals.merge(
    df_cohort[['stay_id','intime']],
    on='stay_id',
    how='left'
)

# keeping only first 24 hours
df_vitals = df_vitals[
    (df_vitals['charttime'] >= df_vitals['intime']) &
    (df_vitals['charttime'] <= df_vitals['intime'] + pd.Timedelta(hours=24))
]

In [23]:
# creating features i.e mean, min, and max

In [24]:
df_vitals_agg = df_vitals.groupby(['stay_id','itemid'])['valuenum'].agg(['mean','min','max']).reset_index()

In [25]:
#converting row to columns

In [26]:
df_vitals_pivot = df_vitals_agg.pivot(index='stay_id', columns='itemid')

# flatten column names
df_vitals_pivot.columns = [
    f"{col[1]}_{col[0]}" for col in df_vitals_pivot.columns
]

df_vitals_pivot = df_vitals_pivot.reset_index()

In [27]:
rename_dict = {
    '220045_mean': 'hr_mean',
    '220045_min': 'hr_min',
    '220045_max': 'hr_max',

    '220210_mean': 'rr_mean',
    '220210_min': 'rr_min',
    '220210_max': 'rr_max',

    '220277_mean': 'spo2_mean',
    '220277_min': 'spo2_min',
    '220277_max': 'spo2_max',

    '220179_mean': 'sbp_mean',
    '220179_min': 'sbp_min',
    '220179_max': 'sbp_max',

    '220180_mean': 'dbp_mean',
    '220180_min': 'dbp_min',
    '220180_max': 'dbp_max',

    '220181_mean': 'mbp_mean',
    '220181_min': 'mbp_min',
    '220181_max': 'mbp_max',
}

df_vitals_pivot = df_vitals_pivot.rename(columns=rename_dict)

In [28]:
df_final = df_cohort.merge(df_vitals_pivot, on='stay_id', how='left')

In [29]:
df_final.head()

,subject_id,hadm_id,seq_num,icd_code,icd_version,stay_id,first_careunit,last_careunit,intime,outtime,...,dbp_min,mbp_min,rr_min,spo2_min,hr_max,sbp_max,dbp_max,mbp_max,rr_max,spo2_max
0,10001884,26184834,10,I469,10,37510196,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2131-01-11 04:20:05,2131-01-20 08:27:30,...,12.0,46.0,10.0,89.0,80.0,180.0,123.0,130.0,26.0,100.0
1,10009823,22096005,13,I469,10,31805686,Neuro Surgical Intensive Care Unit (Neuro SICU),Neuro Surgical Intensive Care Unit (Neuro SICU),2150-12-06 06:46:10,2150-12-06 20:33:52,...,38.0,43.0,12.0,95.0,113.0,145.0,109.0,121.0,30.0,99.0
2,10010471,29842315,3,I462,10,32119961,Coronary Care Unit (CCU),Coronary Care Unit (CCU),2155-12-02 20:33:00,2155-12-07 18:19:18,...,42.0,52.0,9.0,93.0,96.0,139.0,79.0,92.0,24.0,100.0
3,10013569,27993048,2,4275,9,38857852,Coronary Care Unit (CCU),Coronary Care Unit (CCU),2167-11-26 16:26:07,2167-12-05 16:53:53,...,47.0,59.0,10.0,89.0,93.0,126.0,87.0,91.0,24.0,100.0
4,10021454,29492087,1,I469,10,33300154,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2125-03-17 02:41:26,2125-03-24 20:18:57,...,NaN,NaN,19.0,99.0,83.0,NaN,NaN,NaN,23.0,100.0

In [30]:
df_final.shape

(2307, 37)

In [31]:
df_final.columns

Index(['subject_id', 'hadm_id', 'seq_num', 'icd_code', 'icd_version',
       'stay_id', 'first_careunit', 'last_careunit', 'intime', 'outtime',
       'los', 'gender', 'anchor_age', 'anchor_year', 'anchor_year_group',
       'dod', 'deathtime', 'dischtime', 'mortality', 'hr_mean', 'sbp_mean',
       'dbp_mean', 'mbp_mean', 'rr_mean', 'spo2_mean', 'hr_min', 'sbp_min',
       'dbp_min', 'mbp_min', 'rr_min', 'spo2_min', 'hr_max', 'sbp_max',
       'dbp_max', 'mbp_max', 'rr_max', 'spo2_max'],
      dtype='object')

In [32]:
# Adding body temperature in the dataset (BT)
temp_items = [223761, 678]   # Fahrenheit + Celsius   #select temperature itemids
df_temp = df_chartevents[df_chartevents['itemid'].isin(temp_items)]       #FILTER FROM CHARTEVENTS
df_temp = df_temp[df_temp['stay_id'].isin(df_final['stay_id'])]         #KEEP ONLY YOUR COHORT
df_temp['charttime'] = pd.to_datetime(df_temp['charttime'])          #CONVERT TO DATETIME
df_temp = df_temp.merge(                                             #MERGE INTIME (FOR 24h FILTER)
    df_final[['stay_id','intime']],
    on='stay_id',
    how='left'
)
df_temp = df_temp[                                                    #FILTER FIRST 24 HOURS
    (df_temp['charttime'] >= df_temp['intime']) &
    (df_temp['charttime'] <= df_temp['intime'] + pd.Timedelta(hours=24))
]
# Convert Celsius → Fahrenheit                                        #UNIT CONVERSION
df_temp.loc[df_temp['valuenum'] < 50, 'valuenum'] = (
    df_temp['valuenum'] * 9/5 + 32
)
df_temp_agg = df_temp.groupby('stay_id')['valuenum'].agg(['mean','min','max']).reset_index()       #AGGREGATE

df_temp_agg.columns = ['stay_id','bt_mean','bt_min','bt_max']

df_final = df_final.merge(df_temp_agg, on='stay_id', how='left')             #MERGE INTO FINAL DATA

df_final[['bt_mean']].head()

     bt_mean
0        NaN
1  97.533333
2  97.880000
3  98.400000
4  96.500000

In [33]:
# Now we come to cleaning and Aggregration part
# Cleaning the data 
# HR
df_final.loc[(df_final['hr_mean'] < 30) | (df_final['hr_mean'] > 220), 'hr_mean'] = None

# SBP
df_final.loc[(df_final['sbp_mean'] < 50) | (df_final['sbp_mean'] > 250), 'sbp_mean'] = None

# DBP
df_final.loc[(df_final['dbp_mean'] < 30) | (df_final['dbp_mean'] > 150), 'dbp_mean'] = None

# RR
df_final.loc[(df_final['rr_mean'] < 5) | (df_final['rr_mean'] > 60), 'rr_mean'] = None

# SpO2
df_final.loc[(df_final['spo2_mean'] < 50) | (df_final['spo2_mean'] > 100), 'spo2_mean'] = None

# Body Temperature 
df_final.loc[(df_final['bt_mean'] < 80) | (df_final['bt_mean'] > 110), 'bt_mean'] = None

In [34]:
# Select only vital columns
vital_cols = [
    'hr_mean','sbp_mean','dbp_mean','mbp_mean',
    'rr_mean','spo2_mean','bt_mean'
]

# Calculate missing count and percentage
missing_vitals = pd.DataFrame({
    'Missing Count': df_final[vital_cols].isna().sum(),
    'Missing %': (df_final[vital_cols].isna().mean() * 100).round(2)
})

missing_vitals = missing_vitals.reset_index()
missing_vitals.columns = ['Vital Sign','Missing Count','Missing %']

missing_vitals

  Vital Sign  Missing Count  Missing %
0    hr_mean              8       0.35
1   sbp_mean            304      13.18
2   dbp_mean            314      13.61
3   mbp_mean            296      12.83
4    rr_mean             19       0.82
5  spo2_mean             43       1.86
6    bt_mean            621      26.92

In [35]:
# HANDLE MISSING VALUES (INITIAL)
# Mean imputation (low missing)
df_final['hr_mean'] = df_final['hr_mean'].fillna(df_final['hr_mean'].mean())
df_final['dbp_mean'] = df_final['dbp_mean'].fillna(df_final['dbp_mean'].mean())

# Median imputation (skewed)
df_final['sbp_mean'] = df_final['sbp_mean'].fillna(df_final['sbp_mean'].median())
df_final['mbp_mean'] = df_final['mbp_mean'].fillna(df_final['mbp_mean'].median())
df_final['rr_mean'] = df_final['rr_mean'].fillna(df_final['rr_mean'].median())
df_final['spo2_mean'] = df_final['spo2_mean'].fillna(df_final['spo2_mean'].median())

In [36]:
#MBP HARMONIZATION
df_final['mbp_mean'] = df_final['mbp_mean'].fillna(
    (df_final['sbp_mean'] + 2 * df_final['dbp_mean']) / 3
)

In [37]:
df_final.isna().sum()

subject_id             0
hadm_id                0
seq_num                0
icd_code               0
icd_version            0
stay_id                0
first_careunit         0
last_careunit          0
intime                 0
outtime                2
los                    2
gender                 0
anchor_age             0
anchor_year            0
anchor_year_group      0
dod                  638
deathtime            996
dischtime              0
mortality              0
hr_mean                0
sbp_mean               0
dbp_mean               0
mbp_mean               0
rr_mean                0
spo2_mean              0
hr_min                 5
sbp_min              296
dbp_min              296
mbp_min              296
rr_min                15
spo2_min              37
hr_max                 5
sbp_max              296
dbp_max              296
mbp_max              296
rr_max                15
spo2_max              37
bt_mean              621
bt_min               619
bt_max               619
dtype: int64

In [38]:
df_final.columns

Index(['subject_id', 'hadm_id', 'seq_num', 'icd_code', 'icd_version',
       'stay_id', 'first_careunit', 'last_careunit', 'intime', 'outtime',
       'los', 'gender', 'anchor_age', 'anchor_year', 'anchor_year_group',
       'dod', 'deathtime', 'dischtime', 'mortality', 'hr_mean', 'sbp_mean',
       'dbp_mean', 'mbp_mean', 'rr_mean', 'spo2_mean', 'hr_min', 'sbp_min',
       'dbp_min', 'mbp_min', 'rr_min', 'spo2_min', 'hr_max', 'sbp_max',
       'dbp_max', 'mbp_max', 'rr_max', 'spo2_max', 'bt_mean', 'bt_min',
       'bt_max'],
      dtype='object')

In [39]:
#Loading the lab events

lab_chunks = pd.read_csv(
    "C:/MIMIC Structured dataset/mimic-iv-3.1/hosp/labevents.csv",
    usecols=['hadm_id','itemid','charttime','valuenum'],
    chunksize=100000
)

hadm_ids = set(df_final['hadm_id'])

filtered_labs = []

for i, chunk in enumerate(lab_chunks):
    chunk = chunk[chunk['hadm_id'].isin(hadm_ids)]
    filtered_labs.append(chunk)

    if i % 10 == 0:
        print(f"Processed {i} chunks")

df_labs = pd.concat(filtered_labs, ignore_index=True)

Processed 0 chunks
Processed 10 chunks
Processed 20 chunks
Processed 30 chunks
Processed 40 chunks
Processed 50 chunks
Processed 60 chunks
Processed 70 chunks
Processed 80 chunks
Processed 90 chunks
Processed 100 chunks
Processed 110 chunks
Processed 120 chunks
Processed 130 chunks
Processed 140 chunks
Processed 150 chunks
Processed 160 chunks
Processed 170 chunks
Processed 180 chunks
Processed 190 chunks
Processed 200 chunks
Processed 210 chunks
Processed 220 chunks
Processed 230 chunks
Processed 240 chunks
Processed 250 chunks
Processed 260 chunks
Processed 270 chunks
Processed 280 chunks
Processed 290 chunks
Processed 300 chunks
Processed 310 chunks
Processed 320 chunks
Processed 330 chunks
Processed 340 chunks
Processed 350 chunks
Processed 360 chunks
Processed 370 chunks
Processed 380 chunks
Processed 390 chunks
Processed 400 chunks
Processed 410 chunks
Processed 420 chunks
Processed 430 chunks
Processed 440 chunks
Processed 450 chunks
Processed 460 chunks
Processed 470 chunks
Processed 480 chunks
Processed 490 chunks
Processed 500 chunks
Processed 510 chunks
Processed 520 chunks
Processed 530 chunks
Processed 540 chunks
Processed 550 chunks
Processed 560 chunks
Processed 570 chunks
Processed 580 chunks
Processed 590 chunks
Processed 600 chunks
Processed 610 chunks
Processed 620 chunks
Processed 630 chunks
Processed 640 chunks
Processed 650 chunks
Processed 660 chunks
Processed 670 chunks
Processed 680 chunks
Processed 690 chunks
Processed 700 chunks
Processed 710 chunks
Processed 720 chunks
Processed 730 chunks
Processed 740 chunks
Processed 750 chunks
Processed 760 chunks
Processed 770 chunks
Processed 780 chunks
Processed 790 chunks
Processed 800 chunks
Processed 810 chunks
Processed 820 chunks
Processed 830 chunks
Processed 840 chunks
Processed 850 chunks
Processed 860 chunks
Processed 870 chunks
Processed 880 chunks
Processed 890 chunks
Processed 900 chunks
Processed 910 chunks
Processed 920 chunks
Processed 930 chunks
Processed 940 chunks
Processed 950 chunks
Processed 960 chunks
Processed 970 chunks
Processed 980 chunks
Processed 990 chunks
Processed 1000 chunks
Processed 1010 chunks
Processed 1020 chunks
Processed 1030 chunks
Processed 1040 chunks
Processed 1050 chunks
Processed 1060 chunks
Processed 1070 chunks
Processed 1080 chunks
Processed 1090 chunks
Processed 1100 chunks
Processed 1110 chunks
Processed 1120 chunks
Processed 1130 chunks
Processed 1140 chunks
Processed 1150 chunks
Processed 1160 chunks
Processed 1170 chunks
Processed 1180 chunks
Processed 1190 chunks
Processed 1200 chunks
Processed 1210 chunks
Processed 1220 chunks
Processed 1230 chunks
Processed 1240 chunks
Processed 1250 chunks
Processed 1260 chunks
Processed 1270 chunks
Processed 1280 chunks
Processed 1290 chunks
Processed 1300 chunks
Processed 1310 chunks
Processed 1320 chunks
Processed 1330 chunks
Processed 1340 chunks
Processed 1350 chunks
Processed 1360 chunks
Processed 1370 chunks
Processed 1380 chunks
Processed 1390 chunks
Processed 1400 chunks
Processed 1410 chunks
Processed 1420 chunks
Processed 1430 chunks
Processed 1440 chunks
Processed 1450 chunks
Processed 1460 chunks
Processed 1470 chunks
Processed 1480 chunks
Processed 1490 chunks
Processed 1500 chunks
Processed 1510 chunks
Processed 1520 chunks
Processed 1530 chunks
Processed 1540 chunks
Processed 1550 chunks
Processed 1560 chunks
Processed 1570 chunks
Processed 1580 chunks

In [40]:
# selecting the important lab events
lab_items = {
    # Hemoglobin
    50811: 'hemoglobin',
    51222: 'hemoglobin',

    # Hematocrit
    50810: 'hematocrit',
    51221: 'hematocrit',

    # Others
    51265: 'platelet',
    51301: 'wbc',
    51274: 'pt',
    51275: 'inr',
    50912: 'creatinine',
    51006: 'bun',
    50931: 'glucose',
    50971: 'potassium',
    50983: 'sodium',
    50893: 'calcium',
    50902: 'chloride',
    50868: 'anion_gap',
    50882: 'bicarbonate',
    50813: 'lactate',
    50820: 'ph'
}

df_labs = df_labs[df_labs['itemid'].isin(lab_items.keys())]  #filter

In [41]:
df_labs['lab_name'] = df_labs['itemid'].map(lab_items)

In [42]:
# Removing the outliers

df_labs.loc[(df_labs['valuenum'] < 0), 'valuenum'] = None
df_labs.loc[(df_labs['valuenum'] > 600), 'valuenum'] = None  # glucose

In [43]:
# Now aggregating the values of lab events 
df_labs_agg = df_labs.groupby(['hadm_id','lab_name'])['valuenum'].agg(['mean','min','max']).reset_index()

In [44]:
# pivot
df_labs_pivot = df_labs_agg.pivot(index='hadm_id', columns='lab_name')

df_labs_pivot.columns = [
    f"{col[1]}_{col[0]}" for col in df_labs_pivot.columns
]

df_labs_pivot = df_labs_pivot.reset_index()

In [45]:
# merging 
df_final = df_final.merge(df_labs_pivot, on='hadm_id', how='left')

In [46]:
# missing values table for lab events
lab_cols = [
    'hemoglobin_mean','hematocrit_mean','platelet_mean','wbc_mean',
    'pt_mean','inr_mean','creatinine_mean','bun_mean','glucose_mean',
    'potassium_mean','sodium_mean','calcium_mean','chloride_mean',
    'anion_gap_mean','bicarbonate_mean','lactate_mean','ph_mean'
]

missing_labs = pd.DataFrame({
    'Missing Count': df_final[lab_cols].isna().sum(),
    'Missing %': (df_final[lab_cols].isna().mean() * 100).round(2)
})

missing_labs = missing_labs.reset_index()
missing_labs.columns = ['Lab Test','Missing Count','Missing %']

missing_labs

            Lab Test  Missing Count  Missing %
0    hemoglobin_mean             70       3.03
1    hematocrit_mean             69       2.99
2      platelet_mean             75       3.25
3           wbc_mean             71       3.08
4            pt_mean            104       4.51
5           inr_mean            108       4.68
6    creatinine_mean             70       3.03
7           bun_mean             70       3.03
8       glucose_mean             79       3.42
9     potassium_mean             71       3.08
10       sodium_mean             71       3.08
11      calcium_mean             77       3.34
12     chloride_mean             71       3.08
13    anion_gap_mean             73       3.16
14  bicarbonate_mean             73       3.16
15      lactate_mean            210       9.10
16           ph_mean            208       9.02

In [47]:
# Handling the missing values (Lab events)

#Mean imputation (<5%)

mean_cols = missing_labs[missing_labs['Missing %'] < 5]['Lab Test']

for col in mean_cols:
    df_final[col].fillna(df_final[col].mean(), inplace=True)


# Median Imputation (5-10%)
median_cols = missing_labs[
    (missing_labs['Missing %'] >= 5) & (missing_labs['Missing %'] <= 10)
]['Lab Test']

for col in median_cols:
    df_final[col].fillna(df_final[col].median(), inplace=True)

C:\Users\amang\AppData\Local\Temp\ipykernel_14580\3791741155.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final[col].fillna(df_final[col].mean(), inplace=True)
C:\Users\amang\AppData\Local\Temp\ipykernel_14580\3791741155.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final[col].fillna(df_final[col].median(), inplace=True)

In [48]:
# Comorbidities 
df_diag = pd.read_csv("C:/MIMIC Structured dataset/mimic-iv-3.1/hosp/diagnoses_icd.csv")  #LOAD FULL DIAGNOSES DATA

df_diag = df_diag[df_diag['hadm_id'].isin(df_final['hadm_id'])]               #FILTER ONLY YOUR COHORT

df_diag['icd_code'] = df_diag['icd_code'].astype(str)                  #PREPARE ICD CODES

df_diag_grouped = df_diag.groupby('hadm_id')['icd_code'].apply(list).reset_index()           #GROUP ALL DIAGNOSES PER PATIENT

def has_prefix(code_list, prefix):                              #CREATE HELPER FUNCTION
    return any(code.startswith(prefix) for code in code_list)

#CREATE COMORBIDITY FLAGS
df_diag_grouped['copd'] = df_diag_grouped['icd_code'].apply(lambda x: has_prefix(x, 'J44')).astype(int)

df_diag_grouped['heart_failure'] = df_diag_grouped['icd_code'].apply(lambda x: has_prefix(x, 'I50')).astype(int)

df_diag_grouped['diabetes'] = df_diag_grouped['icd_code'].apply(lambda x: has_prefix(x, 'E11')).astype(int)

df_diag_grouped['hypertension'] = df_diag_grouped['icd_code'].apply(lambda x: has_prefix(x, 'I10')).astype(int)

df_comorb = df_diag_grouped[['hadm_id','copd','heart_failure','diabetes','hypertension']]   #KEEP ONLY REQUIRED COLUMNS

df_final = df_final.drop(columns=['copd','heart_failure','diabetes','hypertension'], errors='ignore')    #First remove old incorrect columns

df_final = df_final.merge(df_comorb, on='hadm_id', how='left')   #MERGE INTO FINAL DATASET

df_final[['copd','heart_failure','diabetes','hypertension']] = df_final[      #HANDLE MISSING
    ['copd','heart_failure','diabetes','hypertension']
].fillna(0)

df_final[['copd','heart_failure','diabetes','hypertension']].sum()

copd             151
heart_failure    513
diabetes         400
hypertension     336
dtype: int64

In [49]:
# Treatment Indicator Section
import pandas as pd

# Load inputevents
df_input = pd.read_csv("C:/MIMIC Structured dataset/mimic-iv-3.1/icu/inputevents.csv")

# Keep only cohort
df_input = df_input[df_input['stay_id'].isin(df_final['stay_id'])]

# Merge intime for 24h filter
df_input = df_input.merge(
    df_final[['stay_id','intime']],
    on='stay_id',
    how='left'
)

# Convert datetime
df_input['starttime'] = pd.to_datetime(df_input['starttime'])
df_input['intime'] = pd.to_datetime(df_input['intime'])

# Apply 24-hour filter
df_input = df_input[
    (df_input['starttime'] >= df_input['intime']) &
    (df_input['starttime'] <= df_input['intime'] + pd.Timedelta(hours=24))
]

# Define drug itemids
epinephrine_ids = [221289]
dopamine_ids = [221662]

# Create drug flags
df_input['epinephrine'] = df_input['itemid'].isin(epinephrine_ids).astype(int)
df_input['dopamine'] = df_input['itemid'].isin(dopamine_ids).astype(int)

# Aggregate per patient
df_treat = df_input.groupby('stay_id')[['epinephrine','dopamine']].max().reset_index()

# Ventilation (from chartevents)
vent_items = [224687, 224688]

df_vent = df_chartevents[df_chartevents['itemid'].isin(vent_items)]

# Merge intime
df_vent = df_vent.merge(
    df_final[['stay_id','intime']],
    on='stay_id',
    how='left'
)

# Convert datetime
df_vent['charttime'] = pd.to_datetime(df_vent['charttime'])
df_vent['intime'] = pd.to_datetime(df_vent['intime'])

# Apply 24-hour filter
df_vent = df_vent[
    (df_vent['charttime'] >= df_vent['intime']) &
    (df_vent['charttime'] <= df_vent['intime'] + pd.Timedelta(hours=24))
]

# Create ventilation flag
df_vent['received_ventilation'] = 1

df_vent = df_vent.groupby('stay_id')['received_ventilation'].max().reset_index()

# Merge into final dataset
df_final = df_final.drop(columns=['epinephrine','dopamine','received_ventilation'], errors='ignore')

df_final = df_final.merge(df_treat, on='stay_id', how='left')
df_final = df_final.merge(df_vent, on='stay_id', how='left')

# Fill missing
df_final[['epinephrine','dopamine','received_ventilation']] = df_final[
    ['epinephrine','dopamine','received_ventilation']
].fillna(0)

# Final check
print(df_final[['epinephrine','dopamine','received_ventilation']].mean()*100)

epinephrine             14.824447
dopamine                 9.926311
received_ventilation    73.992198
dtype: float64

In [50]:
# GCS Score

gcs_items = [223900, 223901, 220739]

df_gcs = df_chartevents[df_chartevents['itemid'].isin(gcs_items)]

df_gcs_agg = df_gcs.groupby(['stay_id','itemid'])['valuenum'].mean().reset_index()

df_gcs_pivot = df_gcs_agg.pivot(index='stay_id', columns='itemid', values='valuenum')

df_gcs_pivot.columns = ['gcs_eye','gcs_verbal','gcs_motor']

df_gcs_pivot['gcs_total'] = df_gcs_pivot.sum(axis=1)

df_gcs_pivot = df_gcs_pivot.reset_index()

df_final = df_final.merge(df_gcs_pivot, on='stay_id', how='left')

In [51]:
# Final imputation 

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# Remove non-numeric columns first
cols_to_drop = [
    'subject_id','hadm_id','stay_id',
    'mortality',   # VERY IMPORTANT
    'intime','outtime','dischtime','deathtime','dod'
]

df_model = df_final.drop(columns=cols_to_drop, errors='ignore')
df_model = df_model.select_dtypes(include=['float64','int64'])

imputer = IterativeImputer(max_iter=5, random_state=0)

df_model_imputed = pd.DataFrame(
    imputer.fit_transform(df_model),
    columns=df_model.columns
)

C:\Users\amang\anaconda3\Lib\site-packages\sklearn\impute\_iterative.py:825: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [52]:
df_final[df_model.columns] = df_model_imputed

In [53]:
df_final.shape

(2307, 102)

In [54]:
df_final.isna().sum().sort_values(ascending = False)

deathtime     996
dod           638
outtime         2
subject_id      0
inr_min         0
             ...
dbp_max         0
sbp_max         0
hr_max          0
spo2_min        0
gcs_total       0
Length: 102, dtype: int64

In [55]:
df_final.columns

Index(['subject_id', 'hadm_id', 'seq_num', 'icd_code', 'icd_version',
       'stay_id', 'first_careunit', 'last_careunit', 'intime', 'outtime',
       ...
       'heart_failure', 'diabetes', 'hypertension', 'epinephrine', 'dopamine',
       'received_ventilation', 'gcs_eye', 'gcs_verbal', 'gcs_motor',
       'gcs_total'],
      dtype='object', length=102)

In [57]:
# df_final.to_excel(
#     "C:/Users/amang/mimic_final_dataset1.xlsx",
#     index=False,
#     engine='openpyxl'
# )

In [59]:
df_final.shape

(2307, 102)